modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/MoreIndustrialForegoingAddon/issues"
license="${license}"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/MoreIndustrialForegoingAddon"
    logoFile="icon.png"
    authors="${mod_author}"
    description="${description}"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="industrialforegoing"
    type="required"
    versionRange="ANY"
    ordering="NONE"
    side="BOTH"
[modproperties.${mod_id}]
    catalogueItemIcon="${catalogueItemIcon}"